### ISSUE TITLE
UI Improvement

### ISSUE THREAD

**Issue by Subhampreet** [aromalanil/WhatSend#9]
I would like to contribute to this project and make some UI improvements or UI additions to the project. Hope I can contribute to it.

**Comment by aromalanil** [comment]
@Subhampreet please explain the changes you would like to make stating how it will improve the project.

Do add images/screenshot if possible.

**Comment by aromalanil** [comment]
@Subhampreet Please respond or the issue will be closed soon.

**Comment by Subhampreet** [comment]
Hey @aromalanil, Sorry for the delay in the response, for some unavoidable circumstances I am unable to contribute to the project and discuss my changes with you. You may close the issue, Sorry for the trouble. Thank You!!!
